name: Bandit Check

on:
  push:
  pull_request:

jobs:
  bandit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: Bandit Check (Python security linter)
        uses: jpetrucciani/bandit-check@master
        with:
          path: '/custom_components/ecotrend_ista/'
