name: Bandit Check

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [main]

jobs:
  bandit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Bandit Check (Python security linter)
        uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: "-s B105"
          path: "./custom_components/ecotrend_ista/"
